version: '3.9'

services:
  db:
    image: postgres:16
    container_name: shiplink-db
    ports:
      - "5432:5432"
    env_file:
      - ./env/db/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: shiplink-pgadmin
    image: dpage/pgadmin4
    env_file:
      - ./env/pgadmin/.env
    ports:
      - "8002:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:
